name: android
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v1
        with:
          name: soundcrowd-plugin-spotify.apk
          path: spotify/build/outputs/apk/debug/spotify-debug.apk
